# Generated by Django 5.0.6 on 2024-07-23 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brouillardcaisse_date_cree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to=settings.AUTH_USER_MODEL),
        ),
    ]
